---
- hosts: all
  tasks:
    - name: Git pull
      command: chdir=/root/custom/server{{ serverId }} git pull
    # - name: Update the server ports in docker-compose file
    #   replace:
    #     path: /root/custom/server{{ serverId }}/docker-compose.yml
    #     regexp: "3000:3000"
    #     replace: "300{{ serverId }}:3000"
    - name: Docker Compose up
      command: chdir=/root/custom/server{{ serverId }} docker-compose up --build -d
    # - name: Add the location block in nginx config file
    #   blockinfile:
    #     path: /etc/nginx/sites-available/default
    #     marker: "# Custom Server{{ serverId }} ANSIBLE MANAGED BLOCK"
    #     block: |
    #       location /server{{ serverId }}/custom {
    #           rewrite ^/server{{ serverId }}/custom(.*)$ $1 break;
    #           proxy_pass http://localhost:300{{ serverId }};
    #           proxy_http_version 1.1;
    #           proxy_set_header Upgrade $http_upgrade;
    #           proxy_set_header Connection 'upgrade';
    #           proxy_set_header Host $host;
    #           proxy_cache_bypass $http_upgrade;
    #       }
    #     insertafter: "# Server1 ANSIBLE MANAGED BLOCK"
    # - name: Restart nginx
    #   service:
    #     name: nginx
    #     state: restarted
